USE master
GO
IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'TPI_ECOMMERCE')
BEGIN
    CREATE DATABASE TPI_ECOMMERCE
END
GO

USE TPI_ECOMMERCE
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PRODUCTOS]') AND type in (N'U'))
BEGIN
CREATE TABLE PRODUCTOS (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Nombre VARCHAR(50) NOT NULL,
    Descripcion VARCHAR(200) NULL,
    Precio DECIMAL DEFAULT 0.0 NOT NULL,
    Stock INT DEFAULT 0 NOT NULL,
    Estado BIT DEFAULT 0 NOT NULL,
    UrlImagen VARCHAR(100) NULL
);
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CATEGORIAS]') AND type in (N'U'))
BEGIN
CREATE TABLE CATEGORIAS (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Nombre VARCHAR(50) NOT NULL,
);
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DETALLE_PEDIDOS]') AND type in (N'U'))
BEGIN
CREATE TABLE DETALLE_PEDIDOS (
    Id INT PRIMARY KEY IDENTITY(1,1),
    IdPedido BIGINT FOREIGN KEY REFERENCES PEDIDOS(IdPedido),
    IdProducto INT FOREIGN KEY REFERENCES  PRODUCTOS(IdProducto),
    Cantidad INT NOT NULL
);
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FORMAS_PAGO]') AND type in (N'U'))
BEGIN
CREATE TABLE FORMAS_PAGO(
    Id INT PRIMARY KEY IDENTITY(1,1),
    Nombre VARCHAR(50) NOT NULL,
    Estado VARCHAR(50) DEFAULT 'Falta pago' NOT NULL,
);
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FORMAS_ENTREGA]') AND type in (N'U'))
BEGIN
CREATE TABLE FORMAS_ENTREGA(
    Id INT PRIMARY KEY IDENTITY(1,1),
    Nombre VARCHAR(50) NOT NULL,
    Estado VARCHAR(50) DEFAULT 'Preparando Pedido' NOT NULL
);
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PEDIDOS]') AND type in (N'U'))
BEGIN
CREATE TABLE PEDIDOS (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Fecha DATE NOT NULL DEFAULT GETDATE(),
    Total DECIMAL NOT NULL,
    Estado VARCHAR(30) NOT NULL,
    IdUsuario INT NOT NULL REFERENCES USUARIOS(IdUsuario),
    IdFormaPago INT NOT NULL REFERENCES FORMASPAGO(IdFormaPago),
    IdFormaEntrega INT NOT NULL REFERENCES FORMASENTREGA(IdFormaEntrega),
    IdDireccion INT NULL REFERENCES DIRECCIONES(IdDireccion)
);
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PRODUCTOS]') AND type in (N'U'))
BEGIN
CREATE TABLE OBSERVACION_PEDIDOS(
    Id INT PRIMARY KEY IDENTITY(1,1),
    IdPedido INT FOREIGN KEY REFERENCES PEDIDOS(IdPedido),
    Descripcion VARCHAR(200) NULL,
    Fecha DATETIME NOT NULL DEFAULT GETDATE()
);
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].USUARIOS]') AND type in (N'U'))
BEGIN
CREATE TABLE USUARIOS(
    Id INT PRIMARY KEY IDENTITY(1,1),
    Nombre VARCHAR(50) NOT NULL,
    Apellido VARCHAR(50) NOT NULL,
    Email VARCHAR(70) NOT NULL,
    Pass VARCHAR(20) NOT NULL,
    Telefono VARCHAR(20) NOT NULL,
    Rol SMALLINT NOT NULL
);
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DIRECCIONES]') AND type in (N'U'))
BEGIN
CREATE TABLE DIRECCIONES(
    Id INT PRIMARY KEY IDENTITY(1,1),
    IdUsuario INT FOREIGN KEY REFERENCES USUARIOS(IdUsuario),
    Calle VARCHAR(70) NOT NULL,
    Numero VARCHAR(10) NOT NULL,
    Localidad VARCHAR(50) NOT NULL,
    CodigoPostal VARCHAR(10) NOT NULL,
    Observaciones VARCHAR(100) NOT NULL
);
END
GO